spring.application.name=ch12-ex2

spring.datasource.url=jdbc:mysql://127.0.0.1/spring_quickly
spring.datasource.username=root
spring.datasource.password=4864
#spring.datasource.initialization-mode=always # ? ????? spring boot 2.5ver ???? ?? ? ?
# ???? ???? ???? ?
spring.sql.init.mode=always